### ISSUE TITLE
Hidden directories are showing up.

### ISSUE THREAD

**Issue by mohitYogi** [passy/Android-DirectoryChooser#103]
@passy I don't want directory chooser to show hidden files.
I don't find any config for that. Any leads for that?

**Comment by mohitYogi** [comment]
@passy I think if you modify this one it can hide the hidden files.<br/>
 private boolean isValidFile(final File file) {
        return (file != null && file.isDirectory() && file.canRead() &&
                (mConfig.allowNewDirectoryNameModification() || file.canWrite()) **_&& (mConfig.allowHiddenFiles() || file.toString().startsWith("."))_** );
    }<br/>
Where **_allowHiddenFiles()_** can return a config value given by user.

**Comment by passy** [comment]
I'd like to avoid adding more very specific options. I'd be open to have a generic filter interface that you could implement to filter out directories starting with a dot. Would you be interested in preparing a PR for that?

**Comment by mohitYogi** [comment]
sure.
