### ISSUE TITLE
Crashing on Nexus 6P running Android 8

### ISSUE THREAD

**Issue by SkynetIsACat** [passy/Android-DirectoryChooser#115]
Results in a fatal error when trying to open the activity:

`    final Intent chooserIntent = new Intent(self, DirectoryChooserActivity.class);

                final DirectoryChooserConfig config = DirectoryChooserConfig.builder()
                        .newDirectoryName("")
                        .allowReadOnlyDirectory(true)
                        .allowNewDirectoryNameModification(true)
                        .build();

                chooserIntent.putExtra(DirectoryChooserActivity.EXTRA_CONFIG, config);

                // REQUEST_DIRECTORY is a constant integer to identify the request, e.g. 0
                startActivityForResult(chooserIntent, REQUEST_DIRECTORY);`

Results in:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/gu/option/Option;`

-> `at net.rdrei.android.dirchooser.DirectoryChooserFragment.<init>(DirectoryChooserFragment.java:61)
                                                                                at net.rdrei.android.dirchooser.DirectoryChooserFragment.newInstance(DirectoryChooserFragment.java:91)
                                                                                at net.rdrei.android.dirchooser.DirectoryChooserActivity.onCreate(DirectoryChooserActivity.java:38)`

**Comment by passy** [comment]
dupe https://github.com/passy/Android-DirectoryChooser/issues/86
