### ISSUE TITLE
RuntimeException: Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by HosseinKurd** [passy/Android-DirectoryChooser#125]
After adding this part to AndroidManifest.xml
`<activity android:name="net.rdrei.android.dirchooser.DirectoryChooserActivity"/>`
it shows a RunTime error:
> RuntimeException: Manifest merger failed with multiple errors, see logs

**Comment by josemigueldel85** [comment]
This work for me:

tools:replace="android:theme"

Inside applicationTag
