### ISSUE TITLE
2.x release in maven / sonatype?

### ISSUE THREAD

**Issue by MichaelMalony** [passy/Android-DirectoryChooser#32]
Maybe I'm looking in the wrong place but the latest releases I see in maven and sonatype are 1.0 and 1.0 respectively. Are there no 2.x releases in there?

https://search.maven.org/#browse%7C-1536905800

https://oss.sonatype.org/#nexus-search;quick~net.rdrei.android.dirchooser

**Comment by ParkerK** [comment]
@passy  - it looks like 3.2 snapshots aren't on Sonatype either now?

**Comment by passy** [comment]
I can see them there:

![screenshot 2018-01-26 17 33 15](https://user-images.githubusercontent.com/9906/35452617-04babd96-02bf-11e8-905e-ca5c958fa815.png)
