### ISSUE TITLE
The TextView mTxtvSelectedFolder seems not to be populated.

### ISSUE THREAD

**Issue by martinrevert** [passy/Android-DirectoryChooser#38]
Hi! @passy 

I'm trying to use the library (2.1 version).

All went OK but I'm hitting the following problem: The TextView showing the selected folder is not been populated and refreshed on my app.
Could this be because my theme is not the native Holo? I'm using the AppCompat theme to support legacy Android versions.
<code>
android:theme="@style/Theme.AppCompat"
</code>

Or maybe it is populated but because I'm using a dark AppCompat theme the text is there but not passed to light color?

Thanks for any advice you could give to me.
Martin

**Comment by sloosh** [comment]
same exact issue here ! Calling it from a preference activity, using gradle import...
Any idea ?
Thanks

**Comment by MFlisar** [comment]
I'm using `FragmentActivities` and tried to use the DirectoryChooserActivity... This does not work, no matter which theme... Tried a holo theme, a material theme or an appcompat theme, the text is never visible...

**Comment by passy** [comment]
Please re-open if this is still happening with 3.0.
