### ISSUE TITLE
Error:Artifact 'net.rdrei.android.dirchooser:library:1.0-pre-v11:library.aar' not found.

### ISSUE THREAD

**Issue by m4hmoud** [passy/Android-DirectoryChooser#42]
When I add the compile statement for pre-v11 to Gradle, I get the above error. Am I doing something wrong?

**Comment by jaredsburrows** [comment]
Do you still see this?

**Comment by azatoth77** [comment]
I'm still see this, just now  for pre-v11 release.

If you see the URL that gradle use to find aar file, can you notice that this file is really missing.

https://jcenter.bintray.com/net/rdrei/android/dirchooser/library/1.0-pre-v11/
