### ISSUE TITLE
Target latest API + Material Design

### ISSUE THREAD

**Issue by jaredsburrows** [passy/Android-DirectoryChooser#54]
Target API 22 and Add Material Design

**Comment by passy** [comment]
PR welcome :)

**Comment by jaredsburrows** [comment]
@passy Great! I will do this soon.

**Comment by passy** [comment]
Awesome, thank you!

**Comment by jaredsburrows** [comment]
@passy 
Would you mind the following:
 - Update Robolectric to 3.0-rc3
 - AppCompatv7 - Material Design
 - Use `testCompile` for unit tests
 - Remove Robolectric plugin - not needed

**Comment by jaredsburrows** [comment]
@passy Have you checked out my PR?

**Comment by passy** [comment]
@jaredsburrows Hi, thanks for that! I won't be able to check it out before the weekend. Sorry about that. But it's definitely on my radar. :)

**Comment by jaredsburrows** [comment]
Ok and `Robolectric 3.0 Release` just came out, so I will make a quick update!

**Comment by passy** [comment]
Done!

**Comment by jaredsburrows** [comment]
Thanks!
