### ISSUE TITLE
Theme used in the library conflicts with others

### ISSUE THREAD

**Issue by lfdversluis** [passy/Android-DirectoryChooser#68]
If you use this library you get an error that the app theme is already defined (in my own project). To fix this, you can for example add `tools:replace="android:icon, android:label, android:theme, android:name"` in your application tag in the manifest. However, this causes instability with other libraries such as `com.daimajia.slider:library:1.1.5`.

Giving the error

> Caused by: android.view.InflateException: Binary XML file line #83: Error inflating class com.daimajia.slider.library.SliderLayout

Is there a way to make them all work happily together?

**Comment by avluis** [comment]
Would love to get more info on this as I am attempting to use this library while getting the same errors as above.

**Comment by passy** [comment]
I have not run into this issue. Any input on how we can make this easier for users on the library site would be very welcome.

**Comment by AndreiD** [comment]
`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:15:7-38
	is also present at [net.rdrei.android.dirchooser:library:3.2] AndroidManifest.xml:9:18-62 value=(@style/DirectoryChooserTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:11:3-41:17 to override.`

**Comment by avluis** [comment]
Just wanted to quickly add:

If I use:
compile 'net.rdrei.android.dirchooser:library:2.1@aar'
instead of current, then I can use this library - so changes in between introduces this issue.

**Comment by geeteshk** [comment]
Gentlemen I have found a workaround for those facing this issue. It seems to only show up when android:theme is set for the <application> tag. Remove it and add it to each of your activities separately. Worked fine for me.
