### ISSUE TITLE
Gradle build fails: "Failed to resolve: com.gu:option:1.3"

### ISSUE THREAD

**Issue by BGoll** [passy/Android-DirectoryChooser#76]
The build with gradle in Android studio fails for me with the following error message:

Error:Failed to resolve: com.gu:option:1.3

It looks like the corresponding page in the maven repository is offline: http://mvnrepository.com/artifact/com.gu/option

This is what my build.gradle looks like:

repositories {
    mavenCentral()
    jcenter()
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    [...]
    compile 'com.github.passy:Android-DirectoryChooser:v3.1'
}

**Comment by passy** [comment]
It's available from this maven repo: `https://guardian.github.com/maven/repo-releases`
