### ISSUE TITLE
Gradle compile 3.1 not working

### ISSUE THREAD

**Issue by Scrounger** [passy/Android-DirectoryChooser#79]
Hi @passy,

compile 'net.rdrei.android.dirchooser:library:3.1@aar' not working:

Error:(52, 13) Failed to resolve: net.rdrei.android.dirchooser:library:3.1
<a href="openFile:D:/Projekte/Android/myDepot2/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

compile 'net.rdrei.android.dirchooser:library:2.1'
still works.

Could you please fix it, thanks!

**Comment by passy** [comment]
Confirmed, thanks for the report. Not sure why the artifact disappeared. I'll try to publish a 3.2.

**Comment by passy** [comment]
I've pushed 3.2 and it's already available on Maven. Sorry about this!
