### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [passy/Android-DirectoryChooser#83]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:18:9
	is also present at net.rdrei.android.dirchooser:library:3.2:9:18 value=(@style/DirectoryChooserTheme)
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:14:5 to override

**Comment by passy** [comment]
Please check the existing issues and provide more descriptive titles.
