### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [passy/Android-DirectoryChooser#84]
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment$10: can't find superclass or interface com.gu.option.UnitFunction
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment$11: can't find superclass or interface com.gu.option.UnitFunction
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment$2$1: can't find superclass or interface com.gu.option.UnitFunction
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment: can't find referenced class com.gu.option.Option
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment$10: can't find referenced class com.gu.option.UnitFunction
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment$11: can't find referenced class com.gu.option.UnitFunction
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment$2: can't find referenced class com.gu.option.Option
Warning:net.rdrei.android.dirchooser.DirectoryChooserFragment$2$1: can't find referenced class com.gu.option.UnitFunction
Warning:there were 20 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
:app:proguardDebug FAILED
Error:Execution failed for task ':app:proguardDebug'.
> java.io.IOException: Please correct the above warnings first.

**Comment by passy** [comment]
Please check the existing issues and provide more descriptive titles.
