### ISSUE TITLE
pre-v11 not found

### ISSUE THREAD

**Issue by pzienowicz** [passy/Android-DirectoryChooser#87]
Hi,
I want to use pre-v11 version of this lib.
I have a problem with my gradle sync:
```
Error:Artifact 'library.aar (net.rdrei.android.dirchooser:library:1.0-pre-v11)' not found.
Searched in the following locations:
    https://jcenter.bintray.com/net/rdrei/android/dirchooser/library/1.0-pre-v11/library-1.0-pre-v11.aar
```

When I put gradle link to normal version (11+) it works fine.

**Comment by githubbrowser** [comment]
Same issue here. It looks like the aar file is missing at the address.
Specifying the dependency without aar as in `compile 'net.rdrei.android.dirchooser:library:1.0-pre-v11'` does not work as the other dependencies only work as aar libraries.

> Packaging for dependency com.actionbarsherlock:actionbarsherlock:4.2.0 is 'apklib' and is not supported. Only 'aar' libraries are supported.
> Packaging for dependency com.actionbarsherlock:library:4.2.0 is 'apklib' and is not supported. Only 'aar' libraries are supported.
> Packaging for dependency net.rdrei.android.dirchooser:library:1.0-pre-v11 is 'apklib' and is not supported. Only 'aar' libraries are supported.
> Packaging for dependency com.actionbarsherlock:actionbarsherlock:4.2.0 is 'apklib' and is not supported. Only 'aar' libraries are supported.
> Packaging for dependency com.actionbarsherlock:library:4.2.0 is 'apklib' and is not supported. Only 'aar' libraries are supported.
> Packaging for dependency net.rdrei.android.dirchooser:library:1.0-pre-v11 is 'apklib' and is not supported. Only 'aar' libraries are supported.

@passy, Would it be easy for you to rectify this?

**Comment by passy** [comment]
This library is not available on bintray. You have to add Maven Central to your lookup path. In gradle this would look like this:

```
repositories {
    mavenCentral()
}
```

**Comment by pzienowicz** [comment]
It does not resolve the problem.

> Error:Artifact 'library.aar (net.rdrei.android.dirchooser:library:1.0-pre-v11)' not found.
> Searched in the following locations:
>     https://repo1.maven.org/maven2/net/rdrei/android/dirchooser/library/1.0-pre-v11/library-1.0-pre-v11.aar

**Comment by passy** [comment]
When 1.0 was released, aar wasn't a thing yet. The library is published as
an apklib. You can check for the available versions yourself by omitting
the filename:
https://repo1.maven.org/maven2/net/rdrei/android/dirchooser/library/1.0-pre-v11/
