### ISSUE TITLE
Could not find com.gu:option:1.3.

### ISSUE THREAD

**Issue by jaredsburrows** [passy/Android-DirectoryChooser#88]
Based off #86, since I can't use `@aar`, I am using `compile 'net.rdrei.android.dirchooser:library:3.2'` without the `@aar`. I get the following error, see https://github.com/guardian/Option/issues/2:

```
$ gradle runDebug
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project '<>'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.gu:option:1.3.
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/gu/option/1.3/option-1.3.pom
         https://plugins.gradle.org/m2/com/gu/option/1.3/option-1.3.jar
         https://jitpack.io/com/gu/option/1.3/option-1.3.pom
         https://jitpack.io/com/gu/option/1.3/option-1.3.jar
         file:/<>/.m2/repository/com/gu/option/1.3/option-1.3.pom
         file:/<>/.m2/repository/com/gu/option/1.3/option-1.3.jar
         file:/<>/android-sdk/extras/android/m2repository/com/gu/option/1.3/option-1.3.pom
         file:/<>/android-sdk/extras/android/m2repository/com/gu/option/1.3/option-1.3.jar
         file:/<>/android-sdk/extras/google/m2repository/com/gu/option/1.3/option-1.3.pom
         file:/<>/android-sdk/extras/google/m2repository/com/gu/option/1.3/option-1.3.jar
     Required by:
         :<>:unspecified > net.rdrei.android.dirchooser:library:3.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.188 secs
```

I am forced to add `maven { url 'http://guardian.github.com/maven/repo-releases'  }` in `repositories`.

**Comment by passy** [comment]
This is annoying indeed. I'd like to move away from it for that reason. Does anyone have a suggestion for a different library that provides an option/optional type?

**Comment by jaredsburrows** [comment]
@passy Once they (see https://github.com/guardian/Option/issues/2) publish to jcenter, you should be fine.

**Comment by passy** [comment]
@jaredsburrows Awesome, thanks for raising that!

**Comment by jtakalai** [comment]
Um... why isn't it marked as dependency or something?

**Comment by jaredsburrows** [comment]
@passy This is now marked as help wanted? What did you need help with?

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by ParkerK** [comment]
I had luck using [JitPack](https://jitpack.io/#guardian/Option). 

Add `maven { url 'https://jitpack.io' }` as a repository in the library gradle properties, and 
replace `compile 'com.gu:option:1.3'`
with `compile 'com.github.guardian:Option:-SNAPSHOT'`
